export const FETCHING_IMAGEMARKERDATA = 'FETCHING_IMAGEMARKERDATA';
export const FETCHING_IMAGEMARKERDATA_SUCCESS = 'FETCHING_IMAGEMARKERDATA_SUCCESS';
export const FETCHING_IMAGEMARKERDATA_FAILURE = 'FETCHING_IMAGEMARKERDATA_FAILURE';

export const FETCHING_LOGINDATA = 'FETCHING_LOGINDATA';
export const FETCHING_LOGINDATA_SUCCESS = 'FETCHING_LOGINDATA_SUCCESS';
export const FETCHING_LOGINDATA_FAILURE = 'FETCHING_LOGINDATA_FAILURE';

export const FETCHING_LANGDATA = 'FETCHING_LANGDATA';
export const FETCHING_LANGDATA_SUCCESS = 'FETCHING_LANGDATA_SUCCESS';
export const FETCHING_LANGDATA_FAILURE = 'FETCHING_LANGDATA_FAILURE';

export const FETCHING_FEATURESDATA = 'FETCHING_FEATURESDATA';
export const FETCHING_FEATURESDATA_SUCCESS = 'FETCHING_FEATURESDATA_SUCCESS';
export const FETCHING_FEATURESDATA_FAILURE = 'FETCHING_FEATURESDATA_FAILURE';